# Generated by Django 5.2.7 on 2025-12-07 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_todo_date_added_todo_topic_alter_todo_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoList',
        ),
    ]
